net: can: rockchip: Fixed compilation errors caused by kernel update
drivers/net/can/rockchip/rockchip_canfd:24:24: fatal error:
linux/can/led.h: No such file or directory

Signed-off-by: Elaine Zhang <zhangqing@rock-chips.com>
Change-Id: I275af809bc9287ba2b5855164166aebcb348e259