usb: dwc3: rockchip-inno: remove debugfs directory and host_testmode
This patch remove debugfs directory and host_testmode which
cause the following error:

ERROR: "xhci_set_link_state" [drivers/usb/dwc3/dwc3-rockchip-inno.ko] undefined!

We remove the code of host_testmode directly, because it
depends on the phy_cp_test() which will be dropped later.

As a side effect, we need to use io commands to set the
DWC3 Host enter compliance test mode instead of host_testmode
for RK3328 USB3.

Change-Id: Ie0b1fac63fd6458f07ad30edadc7c4c27486e894
Signed-off-by: William Wu <william.wu@rock-chips.com>