drm/bridge: dw-hdmi-qp: Fixes compilation errors when cec core is not compiled
Fix error: implicit declaration of function 'cec_queue_pin_hpd_event'.

Fixes: b73433e36e58 ("drm/rockchip: Add dw-hdmi-qp driver")
Change-Id: I9268259d42dddd285b3bb8d92a55b7df9ae3c3c1
Signed-off-by: Algea Cao <algea.cao@rock-chips.com>