crypto: rockchip: cryptodev_linux: set vfs-only exports into their own namespace
According to gki commit 176c157bbeb7 ("ANDROID: GKI: set vfs-only exports into their own namespace").

ERROR: modpost: module cryptodev uses symbol __close_fd from namespace VFS_internal_I_am_really_a_filesystem_and_am_NOT_a_driver, but does not import it.

Signed-off-by: Tao Huang <huangtao@rock-chips.com>
Change-Id: Ia796e3c9715468d3a1b7fc89e508ab592b5ebb9f