Fix the error when compiling Edge2 for the first time
ERROR: files are incompatible: Runtime info and framework compatibility matrix are incompatible: No compatible kernel requirement found (kernel FCM version = 8).
For kernel requirements at matrix level 8, For config CONFIG_DEVMEM, value = y but required n

Signed-off-by: Xiong Zhang <xiong.zhang@wesion.com>