mfd: rkx110_x120: ROCKCHIP_SERDES_DRM_PANEL depends on MFD_RKX110_X120
ERROR: modpost: "rkx120_dsi_tx_cmd_seq_xfer" [drivers/mfd/rkx110_x120/rkx110_x120_panel.ko] undefined!

Signed-off-by: Tao Huang <huangtao@rock-chips.com>
Change-Id: I427e0ff85376f38e7877db4ccd01e811e41b14a6